# Generated by Django 4.2.6 on 2023-10-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231027_1322'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='history_book_to_book',
            name='books_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='limit_rent',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='history_book',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.CreateModel(
            name='Rank_Book_To_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_count', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('rank_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rank_book')),
            ],
        ),
        migrations.AddField(
            model_name='rank_book',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
