# Generated by Django 4.2.6 on 2023-10-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_history_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_book',
            name='test',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
