# Generated by Django 4.2.6 on 2023-10-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_history_book_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_book',
            name='test',
        ),
    ]
