# Generated by Django 4.2.6 on 2023-10-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_load_fixtures'),
        ('account', '0004_remove_history_book_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_book',
            name='books',
        ),
        migrations.CreateModel(
            name='History_Book_To_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_count', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('history_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.history_book')),
            ],
        ),
    ]
